### ISSUE TITLE
referencing an EF Core dbcontext w/ nav properties from a dll throws exception

### ISSUE THREAD

**Issue by Sharpiro** [seesharper/csx#3]
Making a new issue for this, and there's a good chance i'm doing something wrong w/ assembly creation, so I apologize ahead of time.

So I've created a dbcontext w/ a few models, and when run as a script it works fine w/ CSX 2.0.  But when I take that dbcontext code, create an assembly, and then reference that assembly I get errors about ```Could not load file or assembly 'System.Core, Version=4.0.0.0```.  No intellisense issues in vs code.

I tried explicitly adding a metadatareference to system.core but no luck.

main.csx:
```
#r "nuget:NetStandard.Library,1.6.1"
#r "nuget:Microsoft.EntityFrameworkCore.SqlServer,1.1.2"
// #r "C:\Users\me\AppData\Local\SqlMapper\generatedAssembly.dll"
#load "other.csx"
// using GeneratedNamespace;

var context = new TempContext();
var query = context.Logs.Take(1);
var list = query.ToList();
```

Here is the code being generated by EF scaffolding that I'm trying to get into a .dll and that i've confirmed works from a ```#load``` script directive.

Other.csx:
```
#r "nuget:NetStandard.Library,1.6.1"
#r "nuget:Microsoft.EntityFrameworkCore.SqlServer,1.1.2"

using Microsoft.EntityFrameworkCore;

public partial class TempContext : DbContext
{
    public virtual DbSet<Log> Logs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Temp;Trusted_Connection=true;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Log>(entity =>
        {
            entity.ToTable("Logs");

            entity.Property(e => e.Value).IsRequired();
        });
    }
}
public partial class Log
{
    public int Id { get; set; }
    public string Value { get; set; }
}
```

Here is how i'm generating the assembly:
https://github.com/Sharpiro/SqlMapper/blob/68224d8fc75573f65e0a261471b1c1cd648f20ee/SourceBuilding.Core/SourceBuilder.cs

Here is the assembly being generated that contains the above dbcontext and models in a 
[generatedAssembly.zip](https://github.com/seesharper/csx/files/1117314/generatedAssembly.zip)

Full Error:
```
csx.ScriptExecutor[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, Pu
blicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
      File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' ---> System.IO.FileNotF
oundException: Could not load the specified file.
      File name: 'System.Core'
         at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
         at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, As
semblyName assemblyName)
         at GeneratedNamespace.TempContext.<>c.<OnModelCreating>b__9_0(EntityTypeBuilder`1 entity)
         at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
         at GeneratedNamespace.TempContext.OnModelCreating(ModelBuilder modelBuilder)
         at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder
 conventionSetBuilder, IModelValidator validator)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
         at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite sco
pedCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCa
llSite constructorCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite sco
pedCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServicePr
ovider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider
 provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvi
der provider)
         at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddQuery>b__1_3(
IServiceProvider p)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite sco
pedCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCa
llSite constructorCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite sco
pedCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
llSite constructorCallSite, ServiceProvider provider)                                                                    pedCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scoovider provider)
pedCallSite, ServiceProvider provider)                                                                                   ider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServicePror)
Se
rviceProvider provider)                                                                                         ider prov
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<Realize(IServiceProv
Service>b__0(                                                                                                   `1 access
ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T]nfrastructure
(IServiceProv
ider provider)
         at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](II
nfrastructure
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<Realize
Service                                                                                            der()
>b__0(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T].csx:line 7
(IServi
ceProvider provider)
         at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IIk task)
nfrastr                                                                                            ext()
ucture`1 accessor)
         at Microsoft.EntityFrameworkCore.DbContext.get_QueryProvider()
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.<.ctor>b__3_0()                 k task)
         at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
         at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TServicerovi
](II
nfrastructure`1 accessor)
         at Microsoft.EntityFrameworkCore.DbContext.get_QueryProvider()                        main
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.<.ctor>b__3_0()
         at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_P
rovi
der()                                                                                          (Tas
         at System.Linq.Queryable.Take[TSource](IQueryable`1 source, Int32 count)
         at Submission#0.<<Initialize>>d__0.MoveNext() in C:\Users\me\Desktop\temp\csxgen\
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_PoveN
rcsx:line 7
ovider()
         at System.Linq.Queryable.Take[TSource](IQueryable`1 source, Int32 count)
         at Submission#0.<<Initialize>>d__0.MoveNext() in C:\Users\me\Desktop\temp\csxgen\(Tas
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
         at System.Linq.Queryable.Take[TSource](IQueryable`1 source, Int32 count)
         at Submission#0.<<Initialize>>d__0.MoveNext() in C:\Users\me\Desktop\temp\csxgen\main.csx:line 7
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
```

**Comment by seesharper** [comment]
Could it be that the generated assembly is not a .Net core assembly?

**Comment by Sharpiro** [comment]
That's definitely possible.  Here's how I'm doing it:
https://github.com/Sharpiro/SqlMapper/blob/68224d8fc75573f65e0a261471b1c1cd648f20ee/SourceBuilding.Core/SourceBuilder.cs

I'm using Roslyn's ```CSharpCompilation.Create``` method, is there a way to use Roslyn to specify that you want to create a .Net core assembly?

**Comment by seesharper** [comment]
Take a look at this SO question suggesting that it might be related to the metadata references used by the compilation. https://stackoverflow.com/questions/34262635/specify-framework-version-for-csharpcompilation-emit

**Comment by seesharper** [comment]
I took a look at the generated assembly using ILSASM and it looks like it references the full framework

```
// Metadata version: v4.0.30319
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern Microsoft.EntityFrameworkCore
{
  .publickeytoken = (AD B9 79 38 29 DD AE 60 )                         // ..y8)..`
  .ver 1:1:2:0
}
.assembly extern System.Core
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern Microsoft.EntityFrameworkCore.SqlServer
{
  .publickeytoken = (AD B9 79 38 29 DD AE 60 )                         // ..y8)..`
  .ver 1:1:2:0
}
.assembly extern Microsoft.EntityFrameworkCore.Relational
{
  .publickeytoken = (AD B9 79 38 29 DD AE 60 )                         // ..y8)..`
  .ver 1:1:2:0
}

```

**Comment by seesharper** [comment]
The SourceMapper.Core project targets both netstandard and net46. The SqlMapper console app is a full framework app and will use the net46 target from SqlMapper.Core and hence the generated assembly will also reference the full framework.

**Comment by Sharpiro** [comment]
Ahh yes that was the issue.  I changed the projects to only target netstandard and found out how to add mscorlib in dotnet core from [this issue](https://github.com/dotnet/roslyn/issues/16211#issuecomment-270510468) and now CSX runs it perfectly. [New SourceBuilder here.](https://github.com/Sharpiro/SqlMapper/commit/e912d76dd7b2eb05244ce61d37a687e8f135c5a3#diff-0010352b30cef5f64ac0bdcd7802be7a)

Although there is one thing that bothers me.  Even though CSX is running it fine, VS code reports an intellisense error.

main.csx:
```
#r "nuget:NetStandard.Library,1.6.1"
#r "nuget:Microsoft.EntityFrameworkCore.SqlServer,1.1.2"
#r "C:\Users\me\AppData\Local\SqlMapper\generatedAssembly.dll"
using Microsoft.EntityFrameworkCore;
using GeneratedNamespace;

var context = new TempContext();
var query = context.Logs.Take(1);
var list = query.ToList();
list.ForEach(WriteLine);
```
The error is on the ```list.ForEach(WriteLine);```:
```
The type 'Object' is defined in an assembly that is not referenced.  You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [main.csx]
```

Writing out the full action as ```list.ForEach(l => WriteLine((object)l));``` will remove the error. Def. a minor issue but still annoying.
[generatedAssembly.zip](https://github.com/seesharper/csx/files/1118067/generatedAssembly.zip)

**Comment by seesharper** [comment]
I might be wrong about this, but I don't think you should reference mscorlib.dll in that way. Is there any way for me to generate the assembly using SqlMapper?

**Comment by Sharpiro** [comment]
I created a new commit [here](https://github.com/Sharpiro/SqlMapper/tree/d7e30b01582bb27fec792e710ee6b2975d5d919e)

[This](https://github.com/Sharpiro/SqlMapper/blob/d7e30b01582bb27fec792e710ee6b2975d5d919e/src/SqlMapper.Cmd/Program.cs) file found in ```SqlMapper.Cmd``` in the solution should create you an assembly, a main script, and an omnisharp.json that can be opened as a folder in vs code.

This will output the assembly w/o the need for a database to exist, but in order to successfully run the script, the database will need to be there.

**Comment by seesharper** [comment]
Tried it and facing the same problem. Still think it is related to how you specify the mscorlib reference. If you take a look at an .Net standard library in ILSPY, you will see that it references System.Runtime rather than directly referencing mscorlib. Unless there is a way to specify System.Runtime during csharp compilation, you might be better off by just scaffold the whole thing as a text source file and compile it with dotnet.exe. Anyway, I think we could close this issue as it is most probably not an issue with this script runner.

**Comment by seesharper** [comment]
![image](https://user-images.githubusercontent.com/1034073/27911397-388d8510-6259-11e7-921a-e5f6e4e333e4.png)
