### ISSUE TITLE
Dependency version error with CSX

### ISSUE THREAD

**Issue by Sharpiro** [seesharper/csx#5]
Summary:

I created a simple example of an error I'm receiving when using CSX.  It seems that regardless of if I use a netstandard or net46 library, CSX tries to load ```Microsoft.Extensions.Logging.Abstractions, Version=1.1.1``` when I'm asking for ```1.1.2``` from my project.

Notes:
- Runs fine from ```csi.exe```
- Changing the version in ```CsxTest.csproj``` to `1.1.1` resolves the error

Script:
```
// #r "C:\Users\user\Desktop\temp\tempProjects\CsxTest\CsxTest\bin\Debug\netstandard1.4\CsxTest.dll"
#r "C:\Users\user\Desktop\temp\tempProjects\CsxTest\CsxTest\bin\Debug\net46\CsxTest.dll"

var logger = new CsxTest.Logger();
```

CsxTest.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net46;netstandard1.4</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="1.1.2" />
  </ItemGroup>

</Project>
```

Logger.cs
```
using System;
using Microsoft.Extensions.Logging;

namespace CsxTest
{
    public class Logger : ILogger
    {
        public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
        {
            Console.WriteLine("Logged Stuff");
        }

        public bool IsEnabled(LogLevel logLevel) => true;

        public IDisposable BeginScope<TState>(TState state) => null;
    }
}
```

Error:
```
fail: csx.ScriptExecutor[0]
      error CS1705: Assembly 'CsxTest' with identity 'CsxTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'M
icrosoft.Extensions.Logging.Abstractions, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Logging.Abstractions' with
 identity 'Microsoft.Extensions.Logging.Abstractions, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

Unhandled Exception: Microsoft.CodeAnalysis.Scripting.CompilationErrorException: error CS1705: Assembly 'CsxTest' with identity 'CsxTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.
Extensions.Logging.Abstractions, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Logging.Abstractions' with identity
 'Microsoft.Extensions.Logging.Abstractions, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at csx.ScriptExecutor.RunScript(Script`1 script, CommandLineScriptGlobals globals) in C:\projects\csx\build\tmp\ScriptExecutor.cs:line 94
   at csx.ScriptExecutor.Execute(String pathToScript, String[] args) in C:\projects\csx\build\tmp\ScriptExecutor.cs:line 85
   at csx.Program.<>c__DisplayClass0_1.<Main>b__4() in C:\projects\csx\build\tmp\Program.cs:line 60
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at csx.Program.Main(String[] args) in C:\projects\csx\build\tmp\Program.cs:line 65
```

**Comment by seesharper** [comment]
Try to reference the logging package from the script 

```
#r "C:\Github\csxtest\bin\Debug\netstandard1.4\CsxTest.dll"
#r "nuget:Microsoft.Extensions.Logging.Abstractions, 1.1.2"

var logger = new CsxTest.Logger();
```

**Comment by Sharpiro** [comment]
That did resolve the issue.

I wonder why it is necessary though.

**Comment by seesharper** [comment]
You can think of it as an assembly redirect forcing the specified version

**Comment by Sharpiro** [comment]
Ok it'd be nice not to have to force the assembly version so that a script that doesn't directly use an assembly wouldn't have to specify it like when using a normal dotnet project.  Do you think this is an issue with CSX or something else?  I can close if you think this is a non-issue.
